### ISSUE TITLE
Emulator not working with ESP/Arduino and U8G2 or other libraries

### ISSUE THREAD

**Issue by jeanroukas** [teeminus/ST7920Emulator#1]
Hi,

I'm writing to inquire about the ST7920Emulator's compatibility with ESP/Arduino boards and the U8g2 library. I'd like to express my appreciation for your contributions to Klipper, the emulator, and your custom firmware - they're invaluable to the community.

I'm currently attempting to use the emulator (on a BTT TFT35 v3.0) with an ESP/Arduino boards and the U8g2 library, but I haven't been successful. I've also experimented with other libraries without achieving the desired results.

I've already opened an issue on the U8g2 GitHub repository ([link here](https://github.com/olikraus/u8g2/issues/2381)) regarding this matter. However, your expertise in this area would be invaluable to me, and I would be happy for any guidance you could offer.

Have you ever tested the ST7920Emulator with an ESP/Arduino board and the U8g2 library or other libraries?
Do you have any suggestions or guidance that might help me troubleshoot my current issues?
Could you point me towards any relevant documentation or resources that might be helpful?
I appreciate your time and consideration, and I look forward to your response.

Thanks,
JR

**Comment by teeminus** [comment]
Hi, I'm sorry, I completely forgot to answer your question.

When I "developed" the NoTouchScreenFirmware I discovered that the allocation/instantiation type seems to matter when using the ST7920Emulator on MCUs. In the example source code, the emulator is instantiated before/outside the main function. You can try moving the instantiation into the main function - that's what I did with the NoTouchScreenFirmware. If that does not help, you can try using dynamic allocation.

You can also check if the callback functions for the emulator are called correctly. If that's not the case, there is something wrong with the emulator instantiation.

I hope that helps solving your problem.

**Comment by jeanroukas** [comment]
Hi Teeminus,

Thanks for your reply. I just want to make sure I understand correctly. Are you suggesting that I should move the "setup" part into the "loop" part? For example, by adding a delay before to make sure the instantiation is done properly?

```
#include "Arduino.h"
#include "U8g2lib.h"

#ifdef U8X8_HAVE_HW_SPI
#include "SPI.h"
#endif
#ifdef U8X8_HAVE_HW_I2C
#include "Wire.h"
#endif

U8G2_ST7920_128X64_1_SW_SPI u8g2(U8G2_R0, /* clock=*/ 7 , /* RW=*/ 11, /* CS=*/ 13, /* reset=*/ 8);

void setup()
{
   u8g2.setBusClock(100000);
   u8g2.begin();
}

void loop()
{
  u8g2.firstPage();
  do {
    u8g2.setFont(u8g2_font_ncenB14_tr);
    u8g2.drawStr(0,24,"Hello World!");
  } while ( u8g2.nextPage() );
  delay(500);
}

```

I'm not sure how to use dynamic allocation with the U8g2 library. Could you please provide some guidance or point me to some relevant documentation?

I appreciate your help.

Best regards,

Jeanroukas

**Comment by teeminus** [comment]
I am not quite sure what you want to achieve.

This library emulates the behavior of a ST7920 display driver. It gets the raw ST7920 command/byte stream as an input and parses it. Using the callback functions, the resulting image can be drawn to any screen/canvas. That's how it works in the NoTouchScreenFirmware. The display gets the SPI data from Klipper/Marlin, parses the data and draws the contents to the TFT screen.

The sample you provided did not look like it is using this library.

**Comment by jeanroukas** [comment]
I want to use the u8g2 library or the library used by Marlin, u8glib, to control a TFT35 display from an ESP/Arduino. I have two unused TFT35 displays (since I switched from Marlin to Klipper). I want to use one of them to control a ceramic kiln. At first, I just want to display a "helloworld" message, like in the code below. In my first post, I also linked to a tutorial that provides more information on how to connect the ESP to the TFT35. I don't know if it's possible, but I've already tried to make it work with my limited knowledge (about 20 hours of research) without success.

**Comment by jeanroukas** [comment]
I want to use the u8g2 library or the library used by Marlin, u8glib, to control a TFT35 display from an ESP/Arduino. I have two unused TFT35 displays (since I switched from Marlin to Klipper). I want to use one of them to control a ceramic kiln. At first, I just want to display a "helloworld" message, like in the code below. In my first post, I also linked to a tutorial that provides more information on how to connect the ESP to the TFT35. I don't know if it's possible, but I've already tried to make it work with my limited knowledge (about 20 hours of research) without success.

**Comment by teeminus** [comment]
I'm sorry, but I have no idea how the u8g2 library works. To use this emulator you just need to be able to draw rectangles on a screen.

I would suggest you first start looking for a display driver for your TFT that lets you draw basic geometric shapes, like lines or fill rectangles. Once you've got that working you can start using the emulator to parse the Klipper/Marlin commands for the ST7920 and draw the resulting image on the screen.

This library is just an interpreter for the ST7920 commands. All graphics and system drivers etc needs to be provided externally. That's why this library is completely platform independent.

**Comment by jeanroukas** [comment]
The u8g2 library is a popular choice for controlling LCD screens, including the ST7920 model with a resolution of 128x64 pixels. I would have expected that connecting the tft35 display emulating the ST7920 would work seamlessly. To complicate matters, Marlin firmware uses the older u8glib library, and my attempts to use it with the tft35 were also unsuccessful.

**Comment by teeminus** [comment]
You need a driver for the screen you are using. Not for the ST7920. Once you can draw on your screen using the correct screen driver you can use this library to parse the Klipper/Marlin ST7920 display commands to draw the result on your screen.
